# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huangquan/code/UAV_detection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huangquan/code/UAV_detection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huangquan/code/UAV_detection/CMakeFiles /home/huangquan/code/UAV_detection//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huangquan/code/UAV_detection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uav_detection

# Build rule for target.
uav_detection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uav_detection
.PHONY : uav_detection

# fast build rule for target.
uav_detection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/build
.PHONY : uav_detection/fast

src/log/RotateFileWriter.o: src/log/RotateFileWriter.cpp.o
.PHONY : src/log/RotateFileWriter.o

# target to build an object file
src/log/RotateFileWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/log/RotateFileWriter.cpp.o
.PHONY : src/log/RotateFileWriter.cpp.o

src/log/RotateFileWriter.i: src/log/RotateFileWriter.cpp.i
.PHONY : src/log/RotateFileWriter.i

# target to preprocess a source file
src/log/RotateFileWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/log/RotateFileWriter.cpp.i
.PHONY : src/log/RotateFileWriter.cpp.i

src/log/RotateFileWriter.s: src/log/RotateFileWriter.cpp.s
.PHONY : src/log/RotateFileWriter.s

# target to generate assembly for a file
src/log/RotateFileWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/log/RotateFileWriter.cpp.s
.PHONY : src/log/RotateFileWriter.cpp.s

src/log/log.o: src/log/log.cpp.o
.PHONY : src/log/log.o

# target to build an object file
src/log/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/log/log.cpp.o
.PHONY : src/log/log.cpp.o

src/log/log.i: src/log/log.cpp.i
.PHONY : src/log/log.i

# target to preprocess a source file
src/log/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/log/log.cpp.i
.PHONY : src/log/log.cpp.i

src/log/log.s: src/log/log.cpp.s
.PHONY : src/log/log.s

# target to generate assembly for a file
src/log/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/log/log.cpp.s
.PHONY : src/log/log.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rtsp/file_source.o: src/rtsp/file_source.cpp.o
.PHONY : src/rtsp/file_source.o

# target to build an object file
src/rtsp/file_source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/file_source.cpp.o
.PHONY : src/rtsp/file_source.cpp.o

src/rtsp/file_source.i: src/rtsp/file_source.cpp.i
.PHONY : src/rtsp/file_source.i

# target to preprocess a source file
src/rtsp/file_source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/file_source.cpp.i
.PHONY : src/rtsp/file_source.cpp.i

src/rtsp/file_source.s: src/rtsp/file_source.cpp.s
.PHONY : src/rtsp/file_source.s

# target to generate assembly for a file
src/rtsp/file_source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/file_source.cpp.s
.PHONY : src/rtsp/file_source.cpp.s

src/rtsp/rtp_source.o: src/rtsp/rtp_source.cpp.o
.PHONY : src/rtsp/rtp_source.o

# target to build an object file
src/rtsp/rtp_source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtp_source.cpp.o
.PHONY : src/rtsp/rtp_source.cpp.o

src/rtsp/rtp_source.i: src/rtsp/rtp_source.cpp.i
.PHONY : src/rtsp/rtp_source.i

# target to preprocess a source file
src/rtsp/rtp_source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtp_source.cpp.i
.PHONY : src/rtsp/rtp_source.cpp.i

src/rtsp/rtp_source.s: src/rtsp/rtp_source.cpp.s
.PHONY : src/rtsp/rtp_source.s

# target to generate assembly for a file
src/rtsp/rtp_source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtp_source.cpp.s
.PHONY : src/rtsp/rtp_source.cpp.s

src/rtsp/rtp_transport.o: src/rtsp/rtp_transport.cpp.o
.PHONY : src/rtsp/rtp_transport.o

# target to build an object file
src/rtsp/rtp_transport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtp_transport.cpp.o
.PHONY : src/rtsp/rtp_transport.cpp.o

src/rtsp/rtp_transport.i: src/rtsp/rtp_transport.cpp.i
.PHONY : src/rtsp/rtp_transport.i

# target to preprocess a source file
src/rtsp/rtp_transport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtp_transport.cpp.i
.PHONY : src/rtsp/rtp_transport.cpp.i

src/rtsp/rtp_transport.s: src/rtsp/rtp_transport.cpp.s
.PHONY : src/rtsp/rtp_transport.s

# target to generate assembly for a file
src/rtsp/rtp_transport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtp_transport.cpp.s
.PHONY : src/rtsp/rtp_transport.cpp.s

src/rtsp/rtspserver.o: src/rtsp/rtspserver.cpp.o
.PHONY : src/rtsp/rtspserver.o

# target to build an object file
src/rtsp/rtspserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtspserver.cpp.o
.PHONY : src/rtsp/rtspserver.cpp.o

src/rtsp/rtspserver.i: src/rtsp/rtspserver.cpp.i
.PHONY : src/rtsp/rtspserver.i

# target to preprocess a source file
src/rtsp/rtspserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtspserver.cpp.i
.PHONY : src/rtsp/rtspserver.cpp.i

src/rtsp/rtspserver.s: src/rtsp/rtspserver.cpp.s
.PHONY : src/rtsp/rtspserver.s

# target to generate assembly for a file
src/rtsp/rtspserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uav_detection.dir/build.make CMakeFiles/uav_detection.dir/src/rtsp/rtspserver.cpp.s
.PHONY : src/rtsp/rtspserver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... uav_detection"
	@echo "... src/log/RotateFileWriter.o"
	@echo "... src/log/RotateFileWriter.i"
	@echo "... src/log/RotateFileWriter.s"
	@echo "... src/log/log.o"
	@echo "... src/log/log.i"
	@echo "... src/log/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/rtsp/file_source.o"
	@echo "... src/rtsp/file_source.i"
	@echo "... src/rtsp/file_source.s"
	@echo "... src/rtsp/rtp_source.o"
	@echo "... src/rtsp/rtp_source.i"
	@echo "... src/rtsp/rtp_source.s"
	@echo "... src/rtsp/rtp_transport.o"
	@echo "... src/rtsp/rtp_transport.i"
	@echo "... src/rtsp/rtp_transport.s"
	@echo "... src/rtsp/rtspserver.o"
	@echo "... src/rtsp/rtspserver.i"
	@echo "... src/rtsp/rtspserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

